### ISSUE TITLE
use command to generate template

### ISSUE THREAD

**Issue by zanvencelj** [trainerlord/worldsystem#124]
**Is your feature request related to a problem? Please describe.**
I want to use the plugin as a generator for 3 diferent types of houses but i cannot because plugin only allows you to generate teplates thru gui. 

**Describe the solution you'd like**
It would be great if there would be a command like /ws get [template name] or /ws give <player> [template name] so world could be generated by admin or console

**Comment by trainerlord** [comment]
That is a feature already in the plugin
in youyr config.yml is multichoose = true?

**Comment by zanvencelj** [comment]
> That is a feature already in the plugin
> in youyr config.yml is multichoose = true?

Yeah but isnt it gui only like console cannot give player world or can it?

**Comment by zanvencelj** [comment]
> /ws get [Name of World]

oh i see i tried that a few weeks ago but it didnt work. i guess i had configs wong...
ty man
